
DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `ID`  bigint(20) NOT NULL AUTO_INCREMENT,
  `PASSWORD` varchar(120) DEFAULT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT '0',
  `FIRST_NAME` varchar(100) DEFAULT NULL,
  `LAST_NAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `USERJSON` text DEFAULT NULL,
  `USERID` varchar(50) DEFAULT NULL,
  `USERTYPE` varchar(20) DEFAULT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `permissions`;

CREATE TABLE `permissions` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PERMISSIONNAME` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PERMISSIONNAME` (`PERMISSIONNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROLENAME` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ROLENAME` (`ROLENAME`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `role_permissions`;

CREATE TABLE `role_permissions` (
  `ROLE_ID` bigint(20) NOT NULL,
  `PERMISSION_ID` bigint(20) NOT NULL,
  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `permissions` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `user_roles`;

CREATE TABLE `user_roles` (
  `USER_ID` bigint(20)  NOT NULL,
  `ROLE_ID` bigint(20)  NOT NULL,
  CONSTRAINT `userrole_user_id_fk1` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `userrole_role_id_fk2` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `verification_token`;

CREATE TABLE `verification_token` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TOKEN` varchar(120) NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `EXPIRY_DATE` TIMESTAMP NOT NULL,
   PRIMARY KEY (`ID`),
   CONSTRAINT `verification_token_user_id_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `user_auth_provider`;

CREATE TABLE `user_auth_provider` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AUTHPROVIDERTYPE` varchar(120) NOT NULL,
  `AUTHPROVIDER_ID` varchar(120) NOT NULL,
  `USER_ID` BIGINT NOT NULL,
   PRIMARY KEY (`ID`),
   CONSTRAINT `user_auth_provider_id_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Client Details SQL https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/test/resources/schema.sql
