  version: '3'

  services:
  
   stufusioncoreserver:
     build: ./core/provision
     image: stufusion/stufusion-core-server
     container_name: stufusioncoreserver
     depends_on:
       - stufusionneo4j
       - kafkaserver
     networks:
      - infracore
     ports:
      - 8085:8085
   

     environment:
      - spring.profiles.active=prod
      - stufusion.core.feedGeneration.topic=feedGeneratorTopic
      - getfolloweeusers_url=test
      - answer_posted_message=test
      - answer_posted_view_url=test
      - EXPOSE_PORT=8081
      - CONTEXT=core-server
      - DB_HOST= stufusionneo4j
      - DB_PORT=7474
      - DB_SECRET=root  
   stufusionneo4j:
     image: neo4j:3.1.0 # pull the latest image
     networks:
      - infracore
     environment:
      - NEO4J_AUTH=neo4j/root # configure the instance with custom username/password
      - dbms.memory.heap.max_size=2048m # configure the heap memory
      - dbms.memory.heap.initial_size=1024m # configure the cache memory
      - dbms.allow_format_migration=true
      - NEO4J_dbms_connector_http_address=0.0.0.0:7474
      - NEO4J_dbms_connectors_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_http_enabled=true
      - NEO4J_dbms_connector_bolt_enabled=true
     volumes:
      - $HOME/neo4j/data:/data # provision the volumes
      - $HOME/neo4j/logs:/logs
     ports: 
      - 7474:7474 # expose the port for the console ui
   stufusiontextvalidatorserver:
     build: ./textvalidator/provision
     image: stufusion/stufusion-textvalidator-server
     container_name: stufusiontextvalidatorserver
     
     networks:
      - infracore
     ports:
      - 7070:7070

   kafkaserver:
     image: spotify/kafka
     container_name: kafka
     hostname: kafkaserver
     ports:
       - 2181:2181
       - 9092:9092
     environment:
       ADVERTISED_HOST: kafkaserver
       ADVERTISED_PORT: 9092
     networks:
      - infracore

   kafka_manager:
     image: "mzagar/kafka-manager-docker:1.3.3.4"
     container_name: kafkamanager
     networks:
      - infracore
     ports:
      - 9000:9000
     depends_on:
      - kafkaserver
     environment:
      ZK_HOSTS: "kafkaserver:2181"
      
   redis:
     image: redis
     container_name: redis
     ports:
      - "6379:6379"   
     volumes:
      - 'redis:/var/lib/redis/data'
     networks:
      - infracore
  
   stufusionauthserver:
    build: ./stufusion-oauth-server/provision
    image: stufusion/stufusion-oauth-server
    container_name: stufusionauthserver
    depends_on:
    - stufusionmysql
   
    networks:
    - infracore
    ports:
    - 9999:9999
    environment:
    - spring.profiles.active=prod
    - EXPOSE_PORT=9999
    - CONTEXT=auth-server
    - DB_HOST=stufusionmysql
    - DB_PORT=3306
    - DB_SECRET=password    
  
    
   stufusionmysql:
     image: library/mysql:latest
     container_name: stufusionmysql
     networks:
     - infracore
     ports:
     - "3306:3306"
     environment:
     - MYSQL_ROOT_PASSWORD=secret
     - MYSQL_DATABASE=authserver
     - MYSQL_USER=test
     - MYSQL_PASSWORD=password              
  networks:
    infracore: 


  volumes:
    redis:  
       
